-- Migration: certifications gain MULTIPLE categories (category -> categories[]),
-- plus more Software Engineering & Data Science certs. Idempotent upsert.
--   psql -h 127.0.0.1 -p 5433 -U cotailor -d cotailor -f apps/api/prisma/cert-catalog-multicat.sql

ALTER TABLE "CertificationCatalog" ADD COLUMN IF NOT EXISTS "categories" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
DROP INDEX IF EXISTS "CertificationCatalog_category_idx";
ALTER TABLE "CertificationCatalog" DROP COLUMN IF EXISTS "category";

-- Full upsert: fixes existing rows' categories/subtypes (incl. the cross-over ML
-- certs) and inserts the new ones. Re-runnable.
INSERT INTO "CertificationCatalog" ("id","name","issuer","level","categories","subtypes","aliases") VALUES
  ('cert_aws_saa','AWS Certified Solutions Architect - Associate','AWS','associate',ARRAY['Software Engineering'],ARRAY['Backend','DevOps','Full Stack'],ARRAY['AWS SAA','SAA-C03','Solutions Architect Associate']),
  ('cert_aws_dva','AWS Certified Developer - Associate','AWS','associate',ARRAY['Software Engineering'],ARRAY['Backend','Full Stack','DevOps'],ARRAY['AWS DVA','DVA-C02']),
  ('cert_aws_devops','AWS Certified DevOps Engineer - Professional','AWS','professional',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['AWS DOP','DOP-C02']),
  ('cert_aws_sysops','AWS Certified SysOps Administrator - Associate','AWS','associate',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['SOA-C02']),
  ('cert_az_204','Microsoft Certified: Azure Developer Associate','Microsoft','associate',ARRAY['Software Engineering'],ARRAY['Backend','Full Stack'],ARRAY['AZ-204','Azure Developer']),
  ('cert_az_104','Microsoft Certified: Azure Administrator Associate','Microsoft','associate',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['AZ-104','Azure Admin']),
  ('cert_az_305','Microsoft Certified: Azure Solutions Architect Expert','Microsoft','professional',ARRAY['Software Engineering'],ARRAY['Backend','DevOps'],ARRAY['AZ-305','Azure Architect']),
  ('cert_gcp_pca','Google Cloud Professional Cloud Architect','Google Cloud','professional',ARRAY['Software Engineering'],ARRAY['Backend','DevOps'],ARRAY['GCP PCA','Professional Cloud Architect']),
  ('cert_gcp_ace','Google Cloud Associate Cloud Engineer','Google Cloud','associate',ARRAY['Software Engineering'],ARRAY['DevOps','Backend'],ARRAY['GCP ACE','Associate Cloud Engineer']),
  ('cert_cka','Certified Kubernetes Administrator','CNCF','single',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['CKA','Kubernetes Administrator']),
  ('cert_ckad','Certified Kubernetes Application Developer','CNCF','single',ARRAY['Software Engineering'],ARRAY['DevOps','Backend'],ARRAY['CKAD']),
  ('cert_terraform','HashiCorp Certified: Terraform Associate','HashiCorp','associate',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['Terraform Associate','HashiCorp Terraform']),
  ('cert_dca','Docker Certified Associate','Docker','associate',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['DCA','Docker Associate']),
  ('cert_rhce','Red Hat Certified Engineer','Red Hat','professional',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['RHCE']),
  ('cert_meta_fe','Meta Front-End Developer Professional Certificate','Meta','single',ARRAY['Software Engineering'],ARRAY['Frontend','Full Stack'],ARRAY['Meta Frontend']),
  ('cert_jsnad','OpenJS Node.js Application Developer','OpenJS Foundation','single',ARRAY['Software Engineering'],ARRAY['Backend','Full Stack'],ARRAY['JSNAD','Node.js Developer']),
  ('cert_java_se','Oracle Certified Professional: Java SE Developer','Oracle','professional',ARRAY['Software Engineering'],ARRAY['Backend'],ARRAY['OCP Java','Java SE']),
  ('cert_mongo_dev','MongoDB Certified Developer Associate','MongoDB','associate',ARRAY['Software Engineering'],ARRAY['Backend','Full Stack'],ARRAY['MongoDB Developer']),
  ('cert_android','Google Associate Android Developer','Google','associate',ARRAY['Software Engineering'],ARRAY['Mobile'],ARRAY['Android Developer']),
  ('cert_security_plus','CompTIA Security+','CompTIA','single',ARRAY['Software Engineering'],ARRAY['DevOps','Backend'],ARRAY['Security Plus','SY0-701']),
  ('cert_cissp','Certified Information Systems Security Professional','(ISC)2','professional',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['CISSP']),
  ('cert_ceh','Certified Ethical Hacker','EC-Council','single',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['CEH']),
  ('cert_aws_sap','AWS Certified Solutions Architect - Professional','AWS','professional',ARRAY['Software Engineering'],ARRAY['Backend','DevOps'],ARRAY['AWS SAP','SAP-C02']),
  ('cert_aws_sec','AWS Certified Security - Specialty','AWS','specialty',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['AWS Security','SCS-C02']),
  ('cert_cks','Certified Kubernetes Security Specialist','CNCF','specialty',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['CKS']),
  ('cert_gcp_devops','Google Cloud Professional DevOps Engineer','Google Cloud','professional',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['GCP DevOps']),
  ('cert_az_400','Microsoft Certified: DevOps Engineer Expert','Microsoft','professional',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['AZ-400','Azure DevOps']),
  ('cert_spring','VMware Spring Professional','VMware','single',ARRAY['Software Engineering'],ARRAY['Backend'],ARRAY['Spring Professional','Spring Certified']),
  ('cert_elastic','Elastic Certified Engineer','Elastic','single',ARRAY['Software Engineering'],ARRAY['Backend','DevOps'],ARRAY['Elasticsearch Engineer']),
  ('cert_github_foundations','GitHub Foundations','GitHub','foundational',ARRAY['Software Engineering'],ARRAY['Frontend','Backend','Full Stack','DevOps'],ARRAY['GitHub Foundations']),
  ('cert_network_plus','CompTIA Network+','CompTIA','single',ARRAY['Software Engineering'],ARRAY['DevOps'],ARRAY['Network Plus','N10-009']),
  ('cert_meta_ios','Meta iOS Developer Professional Certificate','Meta','single',ARRAY['Software Engineering'],ARRAY['Mobile'],ARRAY['Meta iOS','iOS Developer']),
  ('cert_aws_ml','AWS Certified Machine Learning - Specialty','AWS','specialty',ARRAY['Data Science','Software Engineering'],ARRAY['ML Engineer','Research','Backend'],ARRAY['AWS ML','MLS-C01']),
  ('cert_gcp_mle','Google Cloud Professional Machine Learning Engineer','Google Cloud','professional',ARRAY['Data Science','Software Engineering'],ARRAY['ML Engineer','Backend'],ARRAY['GCP PMLE']),
  ('cert_dp_100','Microsoft Certified: Azure Data Scientist Associate','Microsoft','associate',ARRAY['Data Science'],ARRAY['ML Engineer','Research'],ARRAY['DP-100','Azure Data Scientist']),
  ('cert_tf_dev','TensorFlow Developer Certificate','Google','single',ARRAY['Data Science','Software Engineering'],ARRAY['ML Engineer','Research','Backend'],ARRAY['TensorFlow Developer','TF Developer']),
  ('cert_databricks_ml','Databricks Certified Machine Learning Associate','Databricks','associate',ARRAY['Data Science'],ARRAY['ML Engineer'],ARRAY['Databricks ML']),
  ('cert_dp_203','Microsoft Certified: Azure Data Engineer Associate','Microsoft','associate',ARRAY['Data Science','Software Engineering'],ARRAY['Analytics','Data Analyst','Backend'],ARRAY['DP-203','Azure Data Engineer']),
  ('cert_gcp_pde','Google Cloud Professional Data Engineer','Google Cloud','professional',ARRAY['Data Science','Software Engineering'],ARRAY['Analytics','ML Engineer','Backend'],ARRAY['GCP PDE']),
  ('cert_databricks_de','Databricks Certified Data Engineer Associate','Databricks','associate',ARRAY['Data Science','Software Engineering'],ARRAY['Analytics','Backend'],ARRAY['Databricks Data Engineer']),
  ('cert_snowpro','SnowPro Core Certification','Snowflake','single',ARRAY['Data Science'],ARRAY['Analytics','Data Analyst'],ARRAY['SnowPro']),
  ('cert_pl_300','Microsoft Certified: Power BI Data Analyst Associate','Microsoft','associate',ARRAY['Data Science'],ARRAY['Data Analyst','Analytics'],ARRAY['PL-300','Power BI']),
  ('cert_tableau','Tableau Desktop Specialist','Tableau','single',ARRAY['Data Science'],ARRAY['Data Analyst','Analytics'],ARRAY['Tableau']),
  ('cert_aws_da','AWS Certified Data Analytics - Specialty','AWS','specialty',ARRAY['Data Science'],ARRAY['Analytics','Data Analyst'],ARRAY['AWS Data Analytics','DAS-C01']),
  ('cert_databricks_da','Databricks Certified Data Analyst Associate','Databricks','associate',ARRAY['Data Science'],ARRAY['Data Analyst','Analytics'],ARRAY['Databricks Data Analyst']),
  ('cert_databricks_mlp','Databricks Certified Machine Learning Professional','Databricks','professional',ARRAY['Data Science'],ARRAY['ML Engineer'],ARRAY['Databricks ML Professional']),
  ('cert_dp_600','Microsoft Certified: Fabric Analytics Engineer Associate','Microsoft','associate',ARRAY['Data Science'],ARRAY['Analytics','Data Analyst'],ARRAY['DP-600','Fabric Analytics']),
  ('cert_ibm_ds','IBM Data Science Professional Certificate','IBM','single',ARRAY['Data Science'],ARRAY['Data Analyst','ML Engineer'],ARRAY['IBM Data Science']),
  ('cert_google_ada','Google Advanced Data Analytics Professional Certificate','Google','single',ARRAY['Data Science'],ARRAY['Data Analyst','Analytics'],ARRAY['Google Advanced Data Analytics']),
  ('cert_snowpro_ds','SnowPro Advanced: Data Scientist','Snowflake','professional',ARRAY['Data Science'],ARRAY['ML Engineer','Analytics'],ARRAY['SnowPro Data Scientist']),
  ('cert_dbt','dbt Analytics Engineering Certification','dbt Labs','single',ARRAY['Data Science','Software Engineering'],ARRAY['Analytics','Data Analyst','Backend'],ARRAY['dbt','dbt Analytics Engineer']),
  ('cert_sas_ds','SAS Certified Data Scientist','SAS','professional',ARRAY['Data Science'],ARRAY['ML Engineer','Research'],ARRAY['SAS Data Scientist']),
  ('cert_cspo','Certified Scrum Product Owner','Scrum Alliance','single',ARRAY['Product Management'],ARRAY['PM','Technical PM'],ARRAY['CSPO']),
  ('cert_pspo','Professional Scrum Product Owner','Scrum.org','single',ARRAY['Product Management'],ARRAY['PM','APM'],ARRAY['PSPO']),
  ('cert_pragmatic','Pragmatic Institute Certified','Pragmatic Institute','single',ARRAY['Product Management'],ARRAY['PM','Strategy'],ARRAY['PMC']),
  ('cert_safe_popm','SAFe Product Owner/Product Manager','Scaled Agile','single',ARRAY['Product Management'],ARRAY['Technical PM','PM'],ARRAY['SAFe POPM']),
  ('cert_nng_ux','Nielsen Norman Group UX Certification','NN/g','single',ARRAY['Design'],ARRAY['UX','Product Designer'],ARRAY['NN/g UX','NNG UX']),
  ('cert_google_ux','Google UX Design Professional Certificate','Google','single',ARRAY['Design'],ARRAY['UX','UI','Product Designer'],ARRAY['Google UX']),
  ('cert_adobe_acp','Adobe Certified Professional','Adobe','single',ARRAY['Design'],ARRAY['Visual','UI'],ARRAY['ACP','Adobe Certified']),
  ('cert_sf_admin','Salesforce Certified Administrator','Salesforce','single',ARRAY['Sales'],ARRAY['Enterprise','Inside Sales'],ARRAY['SF Admin','ADM-201']),
  ('cert_sf_sales','Salesforce Certified Sales Cloud Consultant','Salesforce','single',ARRAY['Sales'],ARRAY['Enterprise'],ARRAY['Sales Cloud']),
  ('cert_hubspot_sales','HubSpot Sales Software Certification','HubSpot','single',ARRAY['Sales'],ARRAY['SMB','Inside Sales'],ARRAY['HubSpot Sales']),
  ('cert_google_ads','Google Ads Certification','Google','single',ARRAY['Marketing'],ARRAY['Performance','Growth'],ARRAY['Google Ads']),
  ('cert_google_analytics','Google Analytics Certification','Google','single',ARRAY['Marketing'],ARRAY['Growth','Performance'],ARRAY['GA4','Google Analytics']),
  ('cert_hubspot_inbound','HubSpot Inbound Marketing Certification','HubSpot','single',ARRAY['Marketing'],ARRAY['Content','Growth'],ARRAY['HubSpot Inbound']),
  ('cert_meta_blueprint','Meta Certified Digital Marketing Associate','Meta','single',ARRAY['Marketing'],ARRAY['Performance','Growth'],ARRAY['Meta Blueprint']),
  ('cert_pmp','Project Management Professional','PMI','professional',ARRAY['Operations'],ARRAY['Supply Chain','IT Ops'],ARRAY['PMP']),
  ('cert_itil','ITIL 4 Foundation','Axelos','foundational',ARRAY['Operations'],ARRAY['IT Ops'],ARRAY['ITIL','ITIL 4']),
  ('cert_cscp','Certified Supply Chain Professional','ASCM','professional',ARRAY['Operations'],ARRAY['Supply Chain'],ARRAY['CSCP']),
  ('cert_lssgb','Lean Six Sigma Green Belt','ASQ','single',ARRAY['Operations'],ARRAY['Supply Chain','IT Ops'],ARRAY['LSSGB','Six Sigma Green Belt']),
  ('cert_cpa','Certified Public Accountant','AICPA','professional',ARRAY['Finance'],ARRAY['Accounting'],ARRAY['CPA']),
  ('cert_cfa','Chartered Financial Analyst','CFA Institute','professional',ARRAY['Finance'],ARRAY['Investment','Trading'],ARRAY['CFA']),
  ('cert_cma','Certified Management Accountant','IMA','professional',ARRAY['Finance'],ARRAY['FP&A','Accounting'],ARRAY['CMA']),
  ('cert_fmva','Financial Modeling and Valuation Analyst','CFI','single',ARRAY['Finance'],ARRAY['FP&A','Investment'],ARRAY['FMVA']),
  ('cert_frm','Financial Risk Manager','GARP','professional',ARRAY['Finance'],ARRAY['Trading','Investment'],ARRAY['FRM']),
  ('cert_phr','Professional in Human Resources','HRCI','single',ARRAY['Human Resources'],ARRAY['HRBP','Recruiter'],ARRAY['PHR']),
  ('cert_shrm_cp','SHRM Certified Professional','SHRM','single',ARRAY['Human Resources'],ARRAY['HRBP','Recruiter'],ARRAY['SHRM-CP']),
  ('cert_ccp','Certified Compensation Professional','WorldatWork','single',ARRAY['Human Resources'],ARRAY['Compensation'],ARRAY['CCP']),
  ('cert_aptd','Associate Professional in Talent Development','ATD','single',ARRAY['Human Resources'],ARRAY['Learning'],ARRAY['APTD'])
ON CONFLICT ("id") DO UPDATE SET
  name = EXCLUDED.name, issuer = EXCLUDED.issuer, level = EXCLUDED.level,
  categories = EXCLUDED.categories, subtypes = EXCLUDED.subtypes, aliases = EXCLUDED.aliases;
